"""Zaptec Cloud API constants."""

from __future__ import annotations

ZAPTEC_API_BASE = "https://api.zaptec.com"
ZAPTEC_TOKEN_URL = f"{ZAPTEC_API_BASE}/oauth/token"

# State observation IDs (Zaptec API reference).
STATE_IS_ONLINE = 2
STATE_TOTAL_CHARGE_POWER_W = 513
STATE_SESSION_ENERGY_KWH = 553
STATE_CHARGE_CURRENT_A = 708
STATE_CHARGER_OPERATION_MODE = 710
STATE_FINAL_STOP_ACTIVE = 718

# Charger command IDs (Zaptec API reference).
COMMAND_RESTART_CHARGER = 102
COMMAND_STOP_CHARGING_FINAL = 506
COMMAND_RESUME_CHARGING = 507
OPERATION_NO_VEHICLE = 1
OPERATION_REQUESTING = 2
OPERATION_CHARGING = 3
OPERATION_FINISHED = 5
