"""Structured package lifecycle errors."""

from __future__ import annotations


class PackageError(Exception):
    def __init__(self, message: str, *, code: str = "package_error") -> None:
        super().__init__(message)
        self.code = code


INVALID_MANIFEST = "INVALID_MANIFEST"
INCOMPATIBLE_EMIC_VERSION = "INCOMPATIBLE_EMIC_VERSION"
INCOMPATIBLE_MODULE_API_VERSION = "INCOMPATIBLE_MODULE_API_VERSION"
MISSING_DEPENDENCY = "MISSING_DEPENDENCY"
DEPENDENCY_CYCLE = "DEPENDENCY_CYCLE"
INVALID_CAPABILITY = "INVALID_CAPABILITY"
MODULE_ALREADY_INSTALLED = "MODULE_ALREADY_INSTALLED"
MODULE_ID_PROTECTED = "MODULE_ID_PROTECTED"
SIGNATURE_INVALID = "SIGNATURE_INVALID"
MODULE_IN_USE = "MODULE_IN_USE"
PATH_TRAVERSAL = "PATH_TRAVERSAL"
PACKAGE_TOO_LARGE = "PACKAGE_TOO_LARGE"
MODULE_NOT_INSTALLED = "MODULE_NOT_INSTALLED"
ROLLBACK_UNAVAILABLE = "ROLLBACK_UNAVAILABLE"
ENTRYPOINT_MISSING = "ENTRYPOINT_MISSING"
INVALID_PERMISSION = "INVALID_PERMISSION"
PERMISSION_CAPABILITY_MISMATCH = "PERMISSION_CAPABILITY_MISMATCH"
VERSION_DOWNGRADE_NOT_ALLOWED = "VERSION_DOWNGRADE_NOT_ALLOWED"
PUBLISHER_UNKNOWN = "PUBLISHER_UNKNOWN"
PUBLISHER_REVOKED = "PUBLISHER_REVOKED"
MODULE_HAS_DEVICES = "MODULE_HAS_DEVICES"
PACKAGE_LOCKED = "PACKAGE_LOCKED"
PACKAGE_QUARANTINED = "PACKAGE_QUARANTINED"
MIGRATION_REQUIRED = "MIGRATION_REQUIRED"
MIGRATION_FAILED = "MIGRATION_FAILED"
HEALTH_GATE_FAILED = "HEALTH_GATE_FAILED"
CAPABILITY_REMOVAL_BLOCKED = "CAPABILITY_REMOVAL_BLOCKED"
