"""Spa control port."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from energy_core.contracts.spa.status import SpaStatus


@runtime_checkable
class ISpaControl(Protocol):
    async def get_temperature_c(self) -> float | None: ...

    async def set_temperature_c(self, temperature: float) -> None: ...

    async def get_power_w(self) -> float | None: ...

    async def is_heating(self) -> bool: ...


@runtime_checkable
class ISpaControlService(Protocol):
    async def get_status(self) -> SpaStatus: ...

    async def set_target_temperature_c(self, temperature_c: float) -> None: ...

    async def set_pump_state(self, pump: int, state: str) -> None: ...

    async def start_filtering(self) -> None: ...

    async def stop_filtering(self) -> None: ...

    async def ensure_safety_floor(self, *, frequency_per_day: float, duration_hours: float) -> None: ...
