"""EV energy accounting constants."""

from __future__ import annotations

CALCULATION_VERSION = "ev-energy-v1"
ATTRIBUTION_TOLERANCE_KWH = 0.05
ATTRIBUTION_TOLERANCE_FRACTION = 0.02

SESSION_STATUSES = frozenset({"ACTIVE", "COMPLETED", "INCOMPLETE", "ESTIMATED"})
DATA_QUALITIES = frozenset({"MEASURED", "CALCULATED", "ESTIMATED", "INCOMPLETE"})
SAVINGS_BASELINES = frozenset({"IMMEDIATE_GRID_CHARGING", "AVERAGE_GRID_PRICE", "USER_DEFINED"})

DEFAULT_SAVINGS_BASELINE = "IMMEDIATE_GRID_CHARGING"
